<?php

namespace www1601com\Agenturtools;

/**
 * Path: Default location to search for git root (toplevel)
 */
defined('gitPath') or define('gitPath', __DIR__ . '/../../', true);

/**
 * Command: Show the git version
 * @example git version 2.0.4
 */
defined('cmdGitVersion') or define('cmdGitVersion', 'git --version', true);


/**
 * RegEx: Parse the git version
 * @example 2.0.4
 */
defined('regExGitVersion') or define('regExGitVersion', '/git version (.*)/', true);


/**
 * Command: Show the path to the git top-level
 *
 * @example /var/www/project.com/www/
 * @see http://stackoverflow.com/questions/12293944
 */
defined('cmdGitRootPath') or define('cmdGitRootPath', 'git rev-parse --show-toplevel', true);


/**
 * RegEx: Parse the path to the git top-level
 * @example /var/www/project.com/www/
 */
defined('regExGitRootPath') or define('regExGitRootPath', '/(.*)/', true);

/** Command: Get the git status (we only use the headline) */
defined('cmdGitStatus') or define('cmdGitStatus', 'git status -b --porcelain', true);

/** RegEx: Parse the git status headline */
defined('regExGitStatus') or define('regExGitStatus', '## ([\w\d\/\-.]*)(?:\.\.\.)([\w\d\/\-.]*)(?: \[(?:ahead (\d*))?(?:(?:, )?behind (\d*))?\])?', true);

/**
 * Command: Show all files from git status with mode additional information
 * @see http://stackoverflow.com/questions/14141344
 */
defined('cmdGitStatusFiles') or define('cmdGitStatusFiles', 'IFS=\'\'; git status --porcelain | while read -n2 mode; read -n1; read file; do echo MODIFIED=\"$(stat -c %y "$file" 2> /dev/null)\" FILE=\"$file\" MODE=\"$mode\" SIZE=\"$(stat -c %s "$file" 2> /dev/null)\" DISKSIZE=\"$(du -s $file 2> /dev/null)\" TYPE=\"$(stat -c %F "$file" 2> /dev/null)\"; done|sort', true);

/** RegEx: Parse the git status result */
defined('regExGitStatusFiles') or define('regExGitStatusFiles', '/MODIFIED=\"([\d-: ]*).*\" FILE=\"(.*)\" MODE=\".(.)\" SIZE=\"(\d*)\" DISKSIZE=\"(\d*).*\" TYPE=\"(.*)\"/', true);

/** Command: Get the file-diff between filesystem and git, limited to 60 rows */
defined('cmdGitDiff') or define('cmdGitDiff', 'git diff --minimal | head -n60', true);

/** Command: Get the current branch */
defined('cmdGitBranch') or define('cmdGitBranch', 'git branch', true);

/** RegEx: Parse the current branch */
defined('regExGitBranch') or define('regExGitBranch', '/\* (.*)/', true);

/**
 * Parse file-diff
 */
defined('regExGitDiff') or define('regExGitDiff', '/(.*)/', true);

/** Shall the displayed hostname gets determined by gethostname() or by the reverse-dns of the ip of the hostname*/
defined ('getHostnameByReverseDns') or define ('getHostnameByReverseDns', false, true);

/** Only affects customer of the german hoster domainfactory */
defined ('getHostnameWithManagedServerWorkaround') or define ('getHostnameWithManagedServerWorkaround', true, true);

/** Command: Get Hostname by reverse dns. %s will be replaced by the hostname */
defined('cmdGetHostnameByReverseDns') or define('cmdGetHostnameByReverseDns', 'dig +short -x $(dig +short %s)', true);

/** RegEx: Parse the hostname */
defined('regExGetHostnameByReverseDns') or define('regExGetHostnameByReverseDns', '/(.*)\./', true);

/** Text: Reminder text */
defined ('reminderText') or define ('reminderText', "Sorry for disturbing, but [GitSniffer](https://github.com/ADoebeling/Agenturtools) " .
    "found some changes that aren\'t committed yet.\n" .
    "Please review the `git status` / `git diff` below and update your repository. Thanks a lot!\n\n" .

    "**Host:** `%HOSTNAME%` (`%IP%`)\n" .
    "**Path:** `%PATH%`\n" .
    "**Branch:** `%BRANCH%`\n" .
    "**Notification:** %NOTIFICATION%\n\n" .

    "%GITSTATUS%\n\n" .
    "%GITDIFF%\n\n" .

    "<!-- This issue was auto-generated by GitSniffer. (C) @ADoebeling -->", true);

/** Shall someone get mentioned? */
defined('reminderNotification') or define('reminderNotification', '---', true);